-- MySQL Script generated by MySQL Workbench
-- Sun Jan  4 12:58:17 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema iWe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema iWe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iWe` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `iWe` ;

-- -----------------------------------------------------
-- Table `iWe`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iWe`.`Person` (
  `Id` BIGINT(1) NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(32) NOT NULL,
  `FirstName` VARCHAR(25) NULL DEFAULT NULL,
  `LastName` VARCHAR(25) NULL DEFAULT NULL,
  `Birthdate` DATE NULL DEFAULT NULL,
  `PhoneNumber` VARCHAR(13) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `Address` VARCHAR(45) NULL DEFAULT NULL,
  `IsActive` TINYINT(1) NOT NULL,
  `RegistrationDate` TIMESTAMP NULL DEFAULT NULL,
  `LastLogin` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iWe`.`Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iWe`.`Photo` (
  `Id` BIGINT(1) NOT NULL,
  `Description` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iWe`.`WallPost_Likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iWe`.`WallPost_Likes` (
  `Status` TINYINT(1) NULL DEFAULT NULL,
  `WallPost_Id` BIGINT(1) NOT NULL,
  `Person_Id` BIGINT(1) NOT NULL,
  PRIMARY KEY (`WallPost_Id`, `Person_Id`),
  INDEX `fk_WallPost_Like_WallPost1_idx` (`WallPost_Id` ASC),
  INDEX `fk_WallPost_Like_Person1_idx` (`Person_Id` ASC),
  CONSTRAINT `fk_WallPost_Like_WallPost1`
    FOREIGN KEY (`WallPost_Id`)
    REFERENCES `iWe`.`WallPost` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WallPost_Like_Person1`
    FOREIGN KEY (`Person_Id`)
    REFERENCES `iWe`.`Person` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iWe`.`Photo_Likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iWe`.`Photo_Likes` (
  `Person_Id` BIGINT(1) NOT NULL,
  `Photo_Id` BIGINT(1) NOT NULL,
  PRIMARY KEY (`Person_Id`, `Photo_Id`),
  INDEX `fk_Photo_Like_Person1_idx` (`Person_Id` ASC),
  INDEX `fk_Photo_Like_Photo1_idx` (`Photo_Id` ASC),
  CONSTRAINT `fk_Photo_Like_Person1`
    FOREIGN KEY (`Person_Id`)
    REFERENCES `iWe`.`Person` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Photo_Like_Photo1`
    FOREIGN KEY (`Photo_Id`)
    REFERENCES `iWe`.`Photo` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iWe`.`Contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iWe`.`Contact` (
  `Id` BIGINT(1) NOT NULL,
  `Person_Id_1` BIGINT(1) NOT NULL,
  `Person_Id_2` BIGINT(1) NOT NULL,
  `Status` TINYINT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`, `Person_Id_2`, `Person_Id_1`),
  INDEX `PersonI_idx` (`Person_Id_1` ASC),
  INDEX `PersonID2_idx` (`Person_Id_2` ASC),
  CONSTRAINT `PersonID1`
    FOREIGN KEY (`Person_Id_1`)
    REFERENCES `iWe`.`Person` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PersonID2`
    FOREIGN KEY (`Person_Id_2`)
    REFERENCES `iWe`.`Person` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iWe`.`WallPost_Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iWe`.`WallPost_Comment` (
  `Id` BIGINT(1) NOT NULL,
  `IsActive` TINYINT(1) NULL DEFAULT NULL,
  `CreatedDate` TIMESTAMP NULL DEFAULT NULL,
  `ModifiedDate` TIMESTAMP NULL DEFAULT NULL,
  `WallPost_Id` BIGINT(1) NOT NULL,
  `Person_Id` BIGINT(1) NOT NULL,
  PRIMARY KEY (`Id`, `WallPost_Id`, `Person_Id`),
  INDEX `fk_WallPost_Comment_WallPost1_idx` (`WallPost_Id` ASC),
  INDEX `fk_WallPost_Comment_Person1_idx` (`Person_Id` ASC),
  CONSTRAINT `fk_WallPost_Comment_WallPost1`
    FOREIGN KEY (`WallPost_Id`)
    REFERENCES `iWe`.`WallPost` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WallPost_Comment_Person1`
    FOREIGN KEY (`Person_Id`)
    REFERENCES `iWe`.`Person` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iWe`.`WallPost_Comment_Likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iWe`.`WallPost_Comment_Likes` (
  `Status` TINYINT(1) NOT NULL,
  `Person_Id` BIGINT(1) NOT NULL,
  `WallPost_Comment_Id` BIGINT(1) NOT NULL,
  PRIMARY KEY (`Person_Id`, `WallPost_Comment_Id`),
  INDEX `fk_WallPost_Comment_Likes_Person1_idx` (`Person_Id` ASC),
  INDEX `fk_WallPost_Comment_Likes_WallPost_Comment1_idx` (`WallPost_Comment_Id` ASC),
  CONSTRAINT `fk_WallPost_Comment_Likes_Person1`
    FOREIGN KEY (`Person_Id`)
    REFERENCES `iWe`.`Person` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WallPost_Comment_Likes_WallPost_Comment1`
    FOREIGN KEY (`WallPost_Comment_Id`)
    REFERENCES `iWe`.`WallPost_Comment` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
