-- MySQL Script generated by MySQL Workbench
-- Sat Jan  3 19:58:20 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema iWe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema iWe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iWe` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `iWe` ;

-- -----------------------------------------------------
-- Table `iWe`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iWe`.`User` (
  `Id` BIGINT(1) NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(32) NOT NULL,
  `FirstName` VARCHAR(25) NULL DEFAULT NULL,
  `LastName` VARCHAR(25) NULL DEFAULT NULL,
  `Birthdate` DATE NULL DEFAULT NULL,
  `PhoneNumber` VARCHAR(13) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `Address` VARCHAR(45) NULL DEFAULT NULL,
  `IsActive` TINYINT(1) NOT NULL,
  `RegistrationDate` TIMESTAMP NULL DEFAULT NULL,
  `LastLogin` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iWe`.`WallPost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iWe`.`WallPost` (
  `Id` BIGINT(1) NOT NULL AUTO_INCREMENT,
  `Content` MEDIUMTEXT NULL DEFAULT NULL,
  `IsActive` TINYINT(2) NOT NULL,
  `CreatedDate` TIMESTAMP NOT NULL,
  `ModifiedDate` TIMESTAMP NULL DEFAULT NULL,
  `User_Id` BIGINT(1) NOT NULL,
  PRIMARY KEY (`Id`, `User_Id`),
  INDEX `fk_WallPost_User1_idx` (`User_Id` ASC),
  CONSTRAINT `fk_WallPost_User1`
    FOREIGN KEY (`User_Id`)
    REFERENCES `iWe`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iWe`.`Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iWe`.`Photo` (
  `Id` BIGINT(1) NOT NULL,
  `Description` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iWe`.`WallPost_Likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iWe`.`WallPost_Likes` (
  `Status` TINYINT(1) NULL DEFAULT NULL,
  `WallPost_Id` BIGINT(1) NOT NULL,
  `User_Id` BIGINT(1) NOT NULL,
  PRIMARY KEY (`WallPost_Id`, `User_Id`),
  INDEX `fk_WallPost_Thumb_Up_Down_WallPost1_idx` (`WallPost_Id` ASC),
  INDEX `fk_WallPost_Thumb_Up_Down_User1_idx` (`User_Id` ASC),
  CONSTRAINT `fk_WallPost_Thumb_Up_Down_WallPost1`
    FOREIGN KEY (`WallPost_Id`)
    REFERENCES `iWe`.`WallPost` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WallPost_Thumb_Up_Down_User1`
    FOREIGN KEY (`User_Id`)
    REFERENCES `iWe`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iWe`.`Photo_Likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iWe`.`Photo_Likes` (
  `User_Id` BIGINT(1) NOT NULL,
  `Photo_Id` BIGINT(1) NOT NULL,
  PRIMARY KEY (`User_Id`, `Photo_Id`),
  INDEX `fk_Photo_Thumb_Up_Down_User1_idx` (`User_Id` ASC),
  INDEX `fk_Photo_Thumb_Up_Down_Photo1_idx` (`Photo_Id` ASC),
  CONSTRAINT `fk_Photo_Thumb_Up_Down_User1`
    FOREIGN KEY (`User_Id`)
    REFERENCES `iWe`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Photo_Thumb_Up_Down_Photo1`
    FOREIGN KEY (`Photo_Id`)
    REFERENCES `iWe`.`Photo` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iWe`.`Contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iWe`.`Contact` (
  `Id` BIGINT(1) NOT NULL,
  `User_Id_1` BIGINT(1) NOT NULL,
  `User_Id_2` BIGINT(1) NOT NULL,
  `Status` TINYINT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`, `User_Id_2`, `User_Id_1`),
  INDEX `UserI_idx` (`User_Id_1` ASC),
  INDEX `UserID2_idx` (`User_Id_2` ASC),
  CONSTRAINT `UserID1`
    FOREIGN KEY (`User_Id_1`)
    REFERENCES `iWe`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `UserID2`
    FOREIGN KEY (`User_Id_2`)
    REFERENCES `iWe`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iWe`.`WallPost_Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iWe`.`WallPost_Comment` (
  `Id` BIGINT(1) NOT NULL,
  `IsActive` TINYINT(1) NULL DEFAULT NULL,
  `CreatedDate` TIMESTAMP NULL DEFAULT NULL,
  `ModifiedDate` TIMESTAMP NULL DEFAULT NULL,
  `WallPost_Id` BIGINT(1) NOT NULL,
  `User_Id` BIGINT(1) NOT NULL,
  PRIMARY KEY (`Id`, `WallPost_Id`, `User_Id`),
  INDEX `fk_WallPost_Comment_WallPost1_idx` (`WallPost_Id` ASC),
  INDEX `fk_WallPost_Comment_User1_idx` (`User_Id` ASC),
  CONSTRAINT `fk_WallPost_Comment_WallPost1`
    FOREIGN KEY (`WallPost_Id`)
    REFERENCES `iWe`.`WallPost` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WallPost_Comment_User1`
    FOREIGN KEY (`User_Id`)
    REFERENCES `iWe`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iWe`.`WallPost_Comment_Likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iWe`.`WallPost_Comment_Likes` (
  `Status` TINYINT(1) NOT NULL,
  `User_Id` BIGINT(1) NOT NULL,
  `WallPost_Comment_Id` BIGINT(1) NOT NULL,
  PRIMARY KEY (`User_Id`, `WallPost_Comment_Id`),
  INDEX `fk_WallPost_Comment_Likes_User1_idx` (`User_Id` ASC),
  INDEX `fk_WallPost_Comment_Likes_WallPost_Comment1_idx` (`WallPost_Comment_Id` ASC),
  CONSTRAINT `fk_WallPost_Comment_Likes_User1`
    FOREIGN KEY (`User_Id`)
    REFERENCES `iWe`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WallPost_Comment_Likes_WallPost_Comment1`
    FOREIGN KEY (`WallPost_Comment_Id`)
    REFERENCES `iWe`.`WallPost_Comment` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
